name: hotio-qui
services:
  qui:
    container_name: qui
    image: ghcr.io/hotio/qui:release-1.1.0
    ports:
      - target: 7476
        published: "7476"
        protocol: tcp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          label:
            en_US: "User ID"
          description:
            en_US: "The user ID for the container (recommended: 1000)."
          default: "1000"
        - container: PGID
          label:
            en_US: "Group ID"
          description:
            en_US: "The group ID for the container (recommended: 1000)."
          default: "1000"
        - container: TZ
          label:
            en_US: "Timezone"
          description:
            en_US: "Set the timezone for the container."
          default: "America/Los_Angeles"
      ports:
        - container: "7476"
          description:
            en_US: "The internal port for Web interface for qBittorrent."
      volumes:
        - container: /config
          description:
            en_US: "The persistent directory for Web interface for qBittorrent configuration."

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: qui
  category: Hotio
  developer: Hotio
  author: Homelab-Appstore
  tagline:
    en_US: "Web interface for qBittorrent"
  description:
    en_US: |
      🌐 Qui is a modern web UI for qBittorrent, built with React and Node.js.

      It provides a sleek, responsive interface for managing your torrents, with features like drag-and-drop uploads, real-time updates, and mobile support.

      Designed to enhance the qBittorrent experience with a user-friendly alternative to the default web UI.
 
      ➡️ 🔥 [**hotio.dev**](https://hotio.dev/) 🔥

      ➡️ [**GitHub Repo**](https://github.com/acidgreenservers/CasaOS-Hotio-Appstore)

      If you want to create more folders in the Media folder, you may have to run "chmod folder-name 755" on the host machine as root
      in order to give the folder proper permissions for these apps

      **Click The Tips Button On The App Icon in The Apps List For More Info if You Custom Installed**

  icon: "https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/qui.png"
  thumbnail: ""
  screenshot_link: []
  port_map: "7476"
  scheme: http
  title:
    en_US: "Hotio qui"
  tips: {}