name: hotio-caddy
services:
  caddy:
    container_name: caddy
    image: ghcr.io/hotio/caddy:release-2.10.2
    ports:
      - target: 80
        published: "80"
        protocol: tcp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          label:
            en_US: "User ID"
          description:
            en_US: "The user ID for the container (recommended: 1000)."
          default: "1000"
        - container: PGID
          label:
            en_US: "Group ID"
          description:
            en_US: "The group ID for the container (recommended: 1000)."
          default: "1000"
        - container: TZ
          label:
            en_US: "Timezone"
          description:
            en_US: "Set the timezone for the container."
          default: "America/Los_Angeles"
      ports:
        - container: "80"
          description:
            en_US: "The internal port for Web server with automatic HTTPS."
      volumes:
        - container: /config
          description:
            en_US: "The persistent directory for Web server with automatic HTTPS configuration."
        - container: /data
          description:
            en_US: "The persistent directory for Web server with automatic HTTPS configuration."

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: caddy
  category: Hotio
  developer: Hotio
  author: Homelab-Appstore
  tagline:
    en_US: "Web server with automatic HTTPS"
  description:
    en_US: |
      🔒 Caddy is a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go.

      It features HTTP/2, automatic SSL certificate management, and a configuration file that's easy to understand and write.

      Ideal for serving static sites, reverse proxying, and more, Caddy handles HTTPS automatically without complex setup.

      ➡️ 🔥 [**hotio.dev**](https://hotio.dev/) 🔥

      ➡️ [**GitHub Repo**](https://github.com/acidgreenservers/CasaOS-Hotio-Appstore)

      If you want to create more folders in the Media folder, you may have to run "chmod folder-name 755" on the host machine as root
      in order to give the folder proper permissions for these apps

      **Click The Tips Button On The App Icon in The Apps List For More Info if You Custom Installed**

  icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/caddy.png"
  thumbnail: ""
  screenshot_link: []
  port_map: "80"
  scheme: http
  title:
    en_US: "Hotio Caddy"
  tips: {}