name: hotio-base
services:
  base:
    container_name: base
    image: ghcr.io/hotio/base:release
    ports:
      - target: 5800
        published: "5800"
        protocol: tcp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data/Media
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          label:
            en_US: "User ID"
          description:
            en_US: "The user ID for the container (recommended: 1000)."
          default: "1000"
        - container: PGID
          label:
            en_US: "Group ID"
          description:
            en_US: "The group ID for the container (recommended: 1000)."
          default: "1000"
        - container: TZ
          label:
            en_US: "Timezone"
          description:
            en_US: "Set the timezone for the container."
          default: "America/Los_Angeles"
        - container: UMASK
          label:
            en_US: "Umask"
          description:
            en_US: "The umask for the container."
          default: "002"
      ports:
        - container: "5800"
          description:
            en_US: "The internal port for Base image with VPN support."
      volumes:
        - container: /config
          description:
            en_US: "The persistent directory for Base image with VPN support configuration."

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: base
  category: Hotio
  developer: Hotio
  author: Homelab-Appstore
  tagline:
    en_US: "Base image with VPN support"
  description:
    en_US: |
      🏗️ Hotio Base is a foundational Docker image designed for building other containers with built-in VPN support.

      It includes essential tools and configurations for secure, private networking in your homelab applications.

      Perfect for developers creating custom containers that require VPN connectivity for enhanced privacy and access.

      All hotio containers contain a vpn configuration which you can see in the provided screenshot of this app.
      
      **Please use the provided pathing in the before install popup, or when clicking tips on the app in the app list.**
      These containers are setup for consistensy with the servarr [**folder**](https://wiki.servarr.com/en/docker-guide#consistent-and-well-planned-paths) setup

      ➡️ 🔥 [**hotio.dev**](https://hotio.dev/) 🔥

      ➡️ [**GitHub Repo**](https://github.com/acidgreenservers/CasaOS-Hotio-Appstore)

      If you want to create more folders in the Media folder, you may have to run "chmod folder-name 755" on the host machine as root
      in order to give the folder proper permissions for these apps

      **Click The Tips Button On The App Icon in The Apps List For More Info if You Custom Installed**

  icon: "https://hotio.dev/webhook-avatars/pullio.png"
  thumbnail: ""
  screenshot_link: "https://github.com/acidgreenservers/CasaOS-Hotio-Appstore/raw/main/vpn_variables_screenshot.png"
  port_map: "5800"
  scheme: http
  title:
    en_US: "Hotio Base"
  tips: {}